### ISSUE TITLE
"The published version is too low" - why is that an error?

### ISSUE THREAD

**Issue by Riateche** [Hirevo/alexandrie#109] opened 2021-03-30 14:01 UTC
This error prevents publishing new patches for previous minor versions of the crate. For example, if `0.1.0` and `0.2.0` are published, alexandrie refuses to publish `0.1.1`. This is a very common case, and crates.io handles it without issues.

**Comment by damianwadley** [comment] 2022-02-14 23:14
Though this issue was reported before #116 fixed it, the fix is incomplete: alexandrie-index's add_record [still requires that the new version be lower than the latest](https://github.com/Hirevo/alexandrie/blob/721c9a61cb3703ef334e25d7741378c16f0254aa/crates/alexandrie-index/src/tree.rs#L81-L87). Perhaps it would be best to remove that check entirely and let the calling code decide whether it wants to add or not?

**Comment by jcgruenhage** [comment] 2022-02-17 12:22
Aside of whether that should be an error at all: `VersionTooLow` is duplicated in both `alexandrie_index::IndexError` and in `alexandrie::AlexError`. This should be handled in *either* the API *or* the index. The problem that #116 doesn't fix this in all the places is caused by this duplication IMO, so in my fix (PR incoming soon) I've fixed that by removing the check from the index.

**Comment by Hirevo** [comment] 2023-04-13 09:34
This issue is now fixed thanks to the merging of PR **#124** from @jcgruenhage.  
Thanks a lot for the contribution and sorry again for my way too long of a delay.

**Closed by Hirevo** 2023-04-13 09:34 UTC
Labels: C-bug, P-medium, M-api
